### ISSUE TITLE
a key for an annotation with slash in the name

### ISSUE THREAD

**Issue by osher** [breser/git2consul#197]
Hi all.

I hope to find a way to load to consul something that can render with consul-template using `tree | explode | toYAML ` into:

```
deployment:
  annotations:
    vault.security.banzaicloud.io/vault-addr: http://vault-helm.vault.svc:8200
    vault.security.banzaicloud.io/vault-role: applications-role
    vault.security.banzaicloud.io/vault-skip-verify: true
    vault.security.banzaicloud.io/vault-path: kubernetes
```

The problem is obviously, the slash character, which translates into a directory and a file instead of a single file.

Is there a way to use some character that will be replaced to slash as a part of the key name?
without it, we will need to have a special code path to handle just that instead of a simple `tree | explode | toYAML`...

Any point in the right direction will be appreciated :)
